# Generated by Django 4.0 on 2021-12-15 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('razorpaywithdjStripoemailApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffee',
            name='order_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
